PathName  = '/Volumes/data/moore/IPCC/'

models    = {'CCCma_CGCM3T47',       ...
             'CCCma_CGCM3T63',       ...
             'CNRM_CM3',             ...
             'CSIRO_Mk30',           ...
             'GFDL_CM20',            ...
             'GFDL_CM21',            ...
             'GISS_AOM',             ...
             'GISS_EH',              ...
             'GISS_ER',              ...
             'INM_CM30',             ...
             'IPSL_CM4',             ...
             'LASG_FCOALS_g10',      ...
             'MIUB_METRI_MD_ECHO_G', ...
             'MPI_M_ECHAM5_OM',      ...
             'MRI_CGCM232',          ...
             'NCAR_CCSM3',           ...
             'NCAR_PCM',             ...
             'NIES_MIROC32_hires',   ...
             'NIES_MIROC32_medres',  ...
             'UKMO_HadCM3'           };
scenarios = {'A1B','A2','B1'};
% For now, assume run = run1;
%runs      = {'run1','run2'};   

% Obtain User Input
[im,v] = listdlg('PromptString' ,'Select a model:',...
                 'SelectionMode','single',...
                 'ListString'   ,models);

[is,v] = listdlg('PromptString' ,'Select a model:',...
                 'SelectionMode','single',...
                 'ListString'   ,scenarios);

%[ir,v] = listdlg('PromptString' ,'Select a run:',...
%                 'SelectionMode','single',...
%                 'ListString'   ,runs);

byr   = inputdlg('Enter the BEGINNING year (1900-2099):','Year of Project Agro-climate Zone',1,{'2000'});
byr   = str2num(cell2mat(byr));
eyr   = inputdlg('Enter the ENDING year (1900-2099):','Year of Project Agro-climate Zone',1,{'2000'});
eyr   = str2num(cell2mat(eyr));

ButtonName = questdlg('Create Figures and Data file?','Print Flag','yes','no','no');
switch ButtonName,
    case 'yes',
        iprint = 1;
    case 'no',
        iprint = 0;
end
             
fileID = strcat(models(im),'_',scenarios(is),'_')

[lonc,latc,cgdd,map,soilDepth,agz] = agrozones_Douglas(PathName,fileID,byr,eyr,iprint);
%[lonc,latc,cgdd,map,soilDepth,agz] = agrozones_Walden(PathName,fileID,byr,eyr,iprint);

